# -*- coding: utf-8 -*-
"""EDA- Análisis de Datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycHJRh6QfrpAQDKSrwwdnaLITY0j5Al7

# **Paso N°1**
"""

#Importamos librerias
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Conexión a Google Colab
from google.colab import drive
drive.mount('/drive')

"""# **DESCRIPCIÓN DEL CASO**
El conjunto de datos 'Caracteristicas del automovil y MSRP'describe casi 12 000 modelos de automoviles de más de 20 marcas diferentes. El objetivo de este proyecto es comparar entre los automóviles de precio minorista sugerido por el fabricante(MSRP) más alto y más bajo y analizar sus diferencias en función de sus características.

# **Paso N° 2. Cargamos los datos**
"""

#Lectura de datos
df = pd.read_csv('/content/car_dataset.csv')

# Visualizar los datos
df.head()

#  Mostrar las últimas 5 filas del DataFrame
df.tail(5)

# Mostrar cuántas filas y columnas contiene el Data Frame.

df.shape

# Número de filas en ese DataFrame
len(df)

# Obtener una muestra aleatoria de 5 filas de tu DataFrame
df.sample(5)

# Resumen estadístico de las columnas numéricas en un DataFrame
# como la media, la mediana (percentil 50%), los cuartiles (percentiles 25% y 75%), el valor mínimo, el valor máximo y la desviación estándar.

df.describe()

"""# **PASO N°3. Revisando los tipos de datos**

"""

# Mostrar los tipos de datos de cada una de las columnas del DataFrame
df.dtypes

"""# **Paso N°4 Eliminando Columnas**"""

#Se eliminaran las columnas especificadas del DataFrame
df = df.drop(['Engine Fuel Type', 'Market Category','Vehicle Style', 'Popularity', 'Number of Doors', 'Vehicle Size'], axis=1)
df.head(5)

"""# **Paso N° 5. Renombrando columnas**"""

df = df.rename(columns={'Engine HP': 'HP', 'Engine Cylinders': 'Cilindros', 'Transmission Type': 'Transmision', 'Driven_Wheels': 'Tracción', 'highway MPG': 'MPG-H', 'city mpg': 'MPG-C', 'MSRP': 'Precio'})
df.head(5)

"""# **Paso N° 6. Eliminando Registros duplicados**"""

df.shape

df.head(5)

# Eliminar las filas duplicadas del DataFrame
df = df.drop_duplicates()

df.shape

"""# **Paso N°7. Eliminando registros con valores incompletos**"""

# Contar el número de valores no nulos en cada columna del Data Frame
df.count()

# Se observa que HP es 10856
10925 - 10856

#Se observa que  Cilindros es  10 925
10925 - 10895

# Para contar la cantidad de valores nulos (NaN) en cada columna del DataFrame
df.isnull().sum()

# Para eliminar todas las filas que contienen al menos un valor nulo (NaN) en cualquier columna
df = df.dropna()
df.count()

df.isnull().sum()

"""# **Paso N°8. Aplicamos transformaciones**"""

# Llamamos al DF con el nombre de una columna y operar con es columna
df['MPG-H']

# SEe transforman
df['MPG-H'] = df['MPG-H'] * 0.425144

# Se llamna nuevamente
df['MPG-H']

# Lo mismo para la columna MPG-C

df['MPG-C'] = df['MPG-C'] * 0.425144
df['MPG-C']

# Ahora se cambia el nombre
df = df.rename(columns={'MPG-H': 'KPL-R', 'MPG-C': 'KPL-C'})
df.head(5)

"""# **Paso N°9. Detectando valores atípicos**"""

#El diagrama de caja es una visualización útil para representar la distribución de datos y detectar valores atípicos dentro de un conjunto de datos.
sns.boxplot(data=df)

"""Analicemos por separado para evitar el sesgo de Precio"""

# Traza un diagrama de caja para la columna 'Precio', mostrando la distribución de los valores de esa columna.
sns.boxplot(x=df['Precio'])

sns.boxplot(x=df['HP'])

sns.boxplot(x=df['Cilindros'])

"""Analicemos la dispersión del precio que como se ve, tienes valores outliers"""

sns.displot(df['Precio'])
df['Precio'].describe()

sns.boxplot(x=df['Precio'])
df['Precio'].quantile([0, .1, .2, .3, .4, .5, .6, .7, .8, .9, .97, .99, 1])

"""Recortemos los outliers...por ejemplo recortando entre 200 y el cuartil 90% (67 208 como vimos en la celda anterior)"""

corte_inferior = 200
corte_superior = df['Precio'].quantile(0.9)

df = df[(df['Precio'] < corte_superior) & (df['Precio'] > corte_inferior)]

"""Veamos cómo quedó la distribución despues de eliminar los outliers"""

sns.boxplot(x=df['Precio'])

sns.displot(df['Precio'])

"""# **Paso N°10. GRÁFICOS**"""

# Muestra la cantidad de autos por marca
df['Make'].value_counts().plot(kind='bar', figsize=(20,5))
plt.title('Cantidad de autos por marca')
plt.ylabel('Cantidad de autos')
plt.xlabel('Marca')

"""Mapas de correlacion

La matriz de correlación es una tabla que muestra el coeficiente de correlación entre cada par de variables en un conjunto de datos. El coeficiente de correlación varía entre -1 y 1, donde:

1 indica una correlación positiva perfecta.
-1 indica una correlación negativa perfecta.
0 indica que no hay correlación lineal.
"""

correlaciones = df.corr()
sns.heatmap(correlaciones)
correlaciones

"""Dispersión"""

fig, ax = plt.subplots(figsize=(10,6))
ax.scatter(df['HP'], df['Precio'])
ax.set_xlabel('HP')
ax.set_ylabel('Precio')
plt.show()

"""Como vimos a lo largo de este ejeecicio estos son algunos de los pasos que podemos realizar en un análisis exploratorio de datos."""

